# Project Information
site_name: RainPPR's Blog
site_description: by RainPPR
site_author: RainPPR
strict: false

site_url: https://rainppr.github.io/

repo_name: RainPPR/blog
repo_url: https://github.com/RainPPR/blog
edit_uri: edit/main/docs/
copyright: by RainPPR

# Contents
nav:
    - 简介:
        - index.md
        - format.md
        - usage.md
        - discussion.md
        - setting.md
        - static/katex/README.md
    - 数据结构:
        - ds/ds.md
        - 并查集:
            - ds/dsu/dsu1.md
            - ds/dsu/dsu2.md
            - ds/dsu/dsu3.md
        - RMQ 问题:
            - ds/rmq/rmq.md
            - ds/rmq/st.md
        - 树状数组:
            - ds/fenwick/fenwick1.md
        - 线段树:
            - ds/seg/seg1.md
            - ds/seg/seg2.md
            - ds/seg/scanning.md
            - ds/seg/seg_opt.md
            - ds/seg/seg_lichao.md
            - ds/seg/seg_cat.md
        - 珂朵莉树:
            - ds/odt/odt.md
        - ds/sqrt/decomposition.md
        - 离线算法:
            - 莫队:
                - ds/offline/mo/mo_algo.md
                - ds/offline/mo/mo.md
                - ds/offline/mo/mo_tree.md
    - 数学:
        - 线性代数:
            - math/linear-algebra/vector.md
            - math/linear-algebra/matrix.md
            - math/linear-algebra/gauss.md
        - 数论:
            - math/number-theory/index.md
            - math/number-theory/gcd.md
            - math/number-theory/exgcd.md
            - math/number-theory/linear-equation.md
            - math/number-theory/inverse.md
            - math/number-theory/prime.md
            - math/number-theory/euler.md
            - math/number-theory/crt.md
            - math/number-theory/excrt.md
            - math/number-theory/decomposition.md
        - 中学数学:
            - math/whk/sqrt.md
            - math/whk/inverse.md
            - math/whk/trigonometric.md
            - math/whk/sequence.md
    - 图论:
        - 最短路:
            - graph/shortest-path/index.md
            - graph/shortest-path/single.md
            - graph/shortest-path/all.md
            - graph/shortest-path/diff.md
        - 生成树:
            - graph/spanning-tree/mst.md
            - graph/spanning-tree/kruskal.md
        - graph/tree.md
        - graph/dsu-on-tree.md
        - 树分治:
            - graph/divide/point.md

# Theme

# theme:
#     name: material
#     language: 'zh'
#     palette:
#         primary: white
#         accent: red
#         scheme: preference
#     icon:
#         repo: fontawesome/brands/github-alt
#    # logo: static/img/logo.png
#     features:
#         - navigation.tabs
#         - navigation.instant
#         - navigation.tabs.sticky
#         - search.suggest
#         - search.highlight
#         - search.share
#         - content.action.edit
#         - content.code.copy
#         - content.footnote.tooltips
#     include_search_page: false
#     search_index_only: true
#     font:
#         text: 'Segoe UI'
#         code: 'Fira Code'

theme:
    name: null
    custom_dir: 'material/templates'
    static_templates:
        - 404.html
    language: 'zh'
    palette:
        scheme: default
        primary: white
        accent: red
        scheme: preference
    icon:
        repo: fontawesome/brands/github-alt
   # logo: static/img/logo.png
    features:
        - navigation.tabs
        - navigation.instant
        - navigation.tabs.sticky
        - search.suggest
        - search.highlight
        - search.share
        - content.action.edit
        - content.code.copy
        - content.footnote.tooltips
    include_search_page: false
    search_index_only: true
    font:
        text: 'Segoe UI'
        code: 'Fira Code'

plugins:
    - glightbox
    - search
    - minify:
        minify_html: true
#    - mk2pdf-export

# Customization
extra:
    # disqus: 'RainPPR'
    pagetime: 'on'
    manifest: 'manifest.webmanifest'
    githash: ''
    # copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'

extra_javascript:
    - static/js/extra.js

    - static/js/jquery.min.js
    # - static/js/bootstrap.min.js
    # - static/js/fontawesome.min.js

    - static/katex/katex.min.js
    - static/katex/contrib/mhchem.min.js
    - static/katex/contrib/auto-render.min.js
    - static/katex/contrib/copy-tex.min.js

    - static/js/custom.js

extra_css:
    - static/css/extra.css

    - static/css/all.min.css
    - static/katex/katex.min.css

    - static/css/custom.css

# Extensions
markdown_extensions:
    - md_in_html
    - admonition
    - attr_list
    - def_list
    - footnotes
    - meta
    - codehilite:
        guess_lang: false
        linenums: true
    - toc:
        permalink: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.details
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.emoji:
        # emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.smartsymbols
    - pymdownx.snippets:
        check_paths: true
    - pymdownx.progressbar
    - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tabbed:
        alternate_style: true
