# Project Information
site_name: RainPPR's Blog
site_description: by RainPPR
site_author: RainPPR
strict: false

site_url: https://rainppr.github.io/

repo_name: RainPPR/blog
repo_url: https://github.com/RainPPR/blog
edit_uri: blob/master/docs/
# copyright: Copyright &copy; 2016 - 2023 CTF Wiki Team

# Theme
theme:
    name: material
    language: 'zh'
    palette:
        primary: white
        accent: red
        scheme: preference
    icon:
        repo: fontawesome/brands/github-alt
   # logo: static/img/logo.png
    features:
        - tabs: true
        - navigation.tabs
        - navigation.instant
        - navigation.tabs.sticky
        - search.suggest
        - search.highlight
        - search.share
        - content.action.edit
    include_search_page: false
    search_index_only: true
    font:
        text: 'Segoe UI'
        code: 'Fira Code'

# body, text, code {
#     font-family: Consolas, 'Courier New', -apple-system, BlinkMacSystemFont, "San Francisco", "Helvetica Neue", "Noto Sans", "Noto Sans CJK SC",
#     "Noto Sans CJK", "Noto Sans CJK SC", "Source Han Sans", "PingFang SC", "Segoe UI", "Microsoft YaHei", sans-serif !important;
#     /*font-family:  "Noto Sans", "Noto Sans SC", "Noto Sans CJK SC", 'LXGW WenKai GB';*/
# }

plugins:
    - search
    - minify:
        minify_html: true

# Contents
nav:
    - 简介:
        - index.md
        - usage.md
        - discussion.md
        - setting.md
    - 开始:
        - start/hello.md

# Customization
extra:
    disqus: 'RainPPR'
    pagetime: 'on'
    manifest: 'manifest.webmanifest'

extra_javascript:
    #- https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js
    - static/js/extra.js
    - static/js/custom.js
    #- https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
    - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js
    - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
    - https://unpkg.com/katex@0.16.9/dist/katex.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js
    - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
    - https://unpkg.com/katex@0.16.9/dist/contrib/auto-render.min.js


extra_css:
    - static/css/extra.css
    - static/css/custom.css
    - https://cdnjs.cloudflare.com/ajax/libs/normalize-opentype.css/0.2.4/normalize-opentype.min.css
    - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css
    - https://cdn.jsdelivr.net/npm/katex@0.16.6/dist/katex.min.css
    - https://unpkg.com/katex@0.16.9/dist/katex.min.css

# Extensions
markdown_extensions:
    - md_in_html
    - admonition
    - def_list
    - footnotes
    - meta
    - codehilite:
        guess_lang: false
        linenums: true
    - toc:
        permalink: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        # emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols

    - pymdownx.snippets:
        check_paths: true
    - pymdownx.progressbar
    - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.tabbed:
        alternate_style: true
