# Project Information
site_name: RainPPR's Blog
site_description: by RainPPR
site_author: RainPPR
strict: false

site_url: https://rainppr.github.io/blog/

repo_name: RainPPR/blog
repo_url: https://github.com/RainPPR/blog
edit_uri: edit/main/docs/
copyright: by RainPPR

# Contents
nav:
    - 简介:
        - index.md
        - intro/format.md
        - intro/usage.md
        - intro/discussion.md
        - intro/setting.md
    - 比赛相关:
        - contest/pre.md
    - 基础算法:
        - basic/prefix.md
        - basic/xor-hashing.md
    - 动态规划:
        - dp/basic.md
        - dp/sequence.md
        - dp/interval.md
        - dp/opt/mono.md
    - 数据结构:
        - ds/ds.md
        - 并查集:
            - ds/dsu/dsu1.md
            - ds/dsu/dsu2.md
            - ds/dsu/dsu3.md
        - RMQ 问题:
            - ds/rmq/rmq.md
            - ds/rmq/st.md
        - 树状数组:
            - ds/fenwick/fenwick1.md
        - 线段树:
            - ds/seg/seg1.md
            - ds/seg/seg2.md
            - ds/seg/scanning.md
            - ds/seg/seg_opt.md
            - ds/seg/seg_lichao.md
            - ds/seg/seg_cat.md
        - 珂朵莉树:
            - ds/odt/odt.md
        - ds/sqrt/decomposition.md
        - 离线算法:
            - 莫队:
                - ds/offline/mo/mo_algo.md
                - ds/offline/mo/mo.md
                - ds/offline/mo/mo_tree.md
    - 数学:
        - 线性代数:
            - math/linear-algebra/vector.md
            - math/linear-algebra/matrix.md
            - math/linear-algebra/gauss.md
        - 数论:
            - math/number-theory/index.md
            - math/number-theory/qpow.md
            - math/number-theory/gcd.md
            - math/number-theory/exgcd.md
            - math/number-theory/linear-equation.md
            - math/number-theory/inverse.md
            - math/number-theory/prime.md
            - math/number-theory/euler.md
            - math/number-theory/crt.md
            - math/number-theory/excrt.md
            - math/number-theory/decomposition.md
            - math/number-theory/bsgs.md
    - 图论:
        - 最短路:
            - graph/shortest-path/index.md
            - graph/shortest-path/sssp.md
            - graph/shortest-path/apsp.md
            - graph/shortest-path/other.md
            - graph/shortest-path/diff.md
        - 生成树:
            - graph/spanning-tree/mst.md
            - graph/spanning-tree/kruskal.md
        - graph/tree.md
        - graph/dsu-on-tree.md
        - 树分治:
            - graph/divide/point.md
        - 最近公共祖先:
            - graph/lca/index.md
            - graph/lca/binary.md
            - graph/lca/dfs.md

theme:
    name: null
    custom_dir: 'material/templates'
    language: 'zh'
    palette:
        scheme: default
        primary: white
        accent: red
        # scheme: preference
    features:
        - navigation.tabs
        - navigation.instant
        - navigation.tabs.sticky
        - navigation.prune
        - navigation.path
        - search.suggest
        - search.highlight
        - search.share
        - announce.dismiss
        - content.action.edit
        - content.code.copy
        - content.code.select
        - content.footnote.tooltips
        # - header.autohide
    include_search_page: false
    search_index_only: true
    icon:
        repo: fontawesome/brands/github-alt

plugins:
    - glightbox
    - search
    - minify:
        minify_html: true

extra:
    pagetime: 'on'
    manifest: 'manifest.webmanifest'
    githash: ''
    # copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'

extra_javascript:
    - assets/javascripts/extra.js

    - assets/javascripts/jquery.min.js

    - assets/highlight/highlight.min.js

    - assets/katex/katex.min.js
    - assets/katex/contrib/mhchem.min.js
    - assets/katex/contrib/auto-render.min.js
    - assets/katex/contrib/copy-tex.min.js

    - assets/javascripts/custom.js

extra_css:
    - assets/stylesheets/extra.css

    - assets/stylesheets/all.min.css

    - assets/katex/katex.min.css

    - assets/highlight/styles/stackoverflow-light.min.css

    - assets/stylesheets/custom.css

# Extensions
markdown_extensions:
    - md_in_html
    - admonition
    - attr_list
    - def_list
    - footnotes
    - meta
    - codehilite:
        guess_lang: false
        linenums: true
    - toc:
        permalink: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.details
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.highlight:
        anchor_linenums: true
        use_pygments: false
        pygments_lang_class: true
        auto_title: true
        linenums: true
        line_spans: __span
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.smartsymbols
    - pymdownx.snippets:
        check_paths: true
    - pymdownx.progressbar
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tabbed:
        alternate_style: true
