name: Build

on:
    push:
        branches:
            - master
            - main

jobs:
    build:
        name: Page Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout main
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - name: Install Python dependencies
              run: pip install -r ./requirements.txt
            - uses: actions/cache@v4
              with:
                key: ${{ github.ref }}
                path: .cache
            - name: Page Build
              run: |
                mkdocs get-deps>requirements.txt
                mkdocs gh-deploy -v
